### ISSUE TITLE
Built-in logging facility

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#107]
It would be nice to have a built-in logging facility, that would print to the console.

**Comment by ufobat** [comment]
according to p6w there is a p6w.errors that must be used. https://github.com/zostay/P6W#2010-configuration-environment

there is no convenient sub that is could be used to make logging more easy. yeah this is missing.

**Comment by ufobat** [comment]
Log::Any can be uses to do logging within the app. its configured to use the p6w.errors as default. Filters and stuff can be configured either via Bailador::Configuration or you can manually add different log appenders, e.g. to log into a file, before you call `baile()`
