### ISSUE TITLE
Enabled debug mode, port, host  externally

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#110]
Currently the need to be passed to `baile()` which means moving from development to production requires change in the code. A better approach would be to use an environment variable. e.g.

```
BAILADOR=debug,port=5000,host=0.0.0.0
```

**Comment by ufobat** [comment]
just FYI, this is what dancer2 and mojo does with %ENV
* https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Config.pod#Environment-variables
* https://github.com/kraih/mojo/wiki/%25ENV

**Comment by szabgab** [comment]
Later, if that looks more convenient, we can split up and have individual environment variables for each option, but I think it is easier to use if they are in a single env variable.
