### ISSUE TITLE
A configuration file ?

### ISSUE THREAD

**Issue by Emeric54** [Bailador/Bailador#115]
Using a configuration file would be a much easier.

We could imagine a YAML or JSON file, where we could easily puts the main settings of our application, something like : 

```yaml
appname: TestApp
settings:
    debug: True
    port: 3000
    host: 127.0.0.1
```

**Comment by szabgab** [comment]
I am for it with YAML, but I have a few questions that I think we need to answer.

How do you have different configurations for development and production?
How do you make one-off changes to the configuration. (e.g. can you turn off debug mode when in development without changing the file?)

Finally, what do other, similar projects do? What problems have they encountered with configuration and how did they solve them?

**Comment by Emeric54** [comment]
> How do you have different configurations for development and production?

We could imagine differents filenames. For exammple, `settings.yaml` for development, and `settings_prod.yaml` for the production. Just to give a reference, this technique is often used in Django Projects.

> e.g. can you turn off debug mode when in development without changing the file?)

I don't know if it's really needed ?

> Finally, what do other, similar projects do?

I believe it was possible to use a similar file with Dancer2.
Same thing for Sinatra : 
```yaml
development:
  foo: development
  bar: bar
test:
  foo: test
  bar: bar
production:
  foo: production
  bar: bar
```
This configuration is interesting. It'd allow to have several environments configurations in the same file. Why not with Bailador ?

**Comment by szabgab** [comment]
Another issue that at one point needs to be addressed is secret configuration values. Certain values can be included in a publicly readable (e.g. in GitHub) config file. Other values should not be available that way. (e.g. API keys) We don't have to solve this problem right away, but would be nice to have at least a description of recommended solution.

**Comment by ufobat** [comment]
its probably a good idea to stay close to http://search.cpan.org/dist/Dancer2/lib/Dancer2/Config.pod

**Comment by ufobat** [comment]
when you select the configuration file depending on the mode, you can not set the mode in the configuration file, right?

**Comment by ufobat** [comment]
added Bailador::Configuration in fa4a278ec0d974eb3afd6cc7d6276592367a5bb1

**Comment by ufobat** [comment]
There are some config settings stored an Array. What is the right behaviour? 

Eg if you want to "Push" a value 'a' via Env, maybe "Push" the value 'b' and 'c' via config file, and maybe you like to discard a Default value 'x' that is already in the configuration object.

**Comment by ufobat** [comment]
currently we evaluate ENV and then the file. because you could state the config-file in env.
this means that things in the config file _always_ override the settings from ENV. is this _always_ the right thing?

**Comment by szabgab** [comment]
I think ENV variables should always override any other configuration value.

**Comment by ufobat** [comment]
I agree, so should we have an additional ENV variable like
`BAILADOR_CONFIGFILE` that gets evaluated first, so we could use this in order to change the config file?
