### ISSUE TITLE
Dynamic vars $*PROGRAM and $*PROGRAM-NAME are not showing correctly

### ISSUE THREAD

**Issue by chsanch** [Bailador/Bailador#119]
Executing  _bailador_ without arguments, I'm, getting the following output:

```
$ bailador
Usage:
    /Users/chsanch/.rakudobrew/moar-2017.05/install/share/perl6/site/resources/71985446A5DBC3EB1694DCE3776293A522E54A58 --help         (shows this help)
    /Users/chsanch/.rakudobrew/moar-2017.05/install/share/perl6/site/resources/71985446A5DBC3EB1694DCE3776293A522E54A58 Project-Name   (creates a directory called Project-Name with a skeleton application)
```
I'm using _rakudobrew_ to manage Perl6 versions, and _zef_ as a package manager

```
$ perl6 --version
This is Rakudo version 2017.05 built on MoarVM version 2017.05
implementing Perl 6.c.
```

**Comment by szabgab** [comment]
Same on OSX using zef on Rakudo Start 2017.04

The original program Bailador supplies is installed as that horrible long name which can be seen in the usage message. The program which is installed as "bailador" is some standardized code snippet created by the installation (zef ?). That launches the actual script using run().

So $*PROGRAM-NAME is correctly showing that long and horrible name,
but that's rather useless for the end-user.

zef itself solves this problem by including the name 'zef' in the usage message and not relying on the $*PROGRAM-NAME.  This can be a solution for us as well, but let's see if we get some other solution:

I've asked about this on the perl6-users list:
http://www.nntp.perl.org/group/perl.perl6.users/2017/05/msg3828.html

**Comment by szabgab** [comment]
See also https://github.com/perl6/ecosystem/issues/304

**Comment by szabgab** [comment]
The way bailador is written now, we don't see this issue any more in 0.0.10
