### ISSUE TITLE
Make Bailador installable from CPAN

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#135]
See https://github.com/ugexe/zef/issues/173#issuecomment-307569086

Specifically read:
https://github.com/ugexe/zef#cpan
http://ugexe.com/perl-toolchain-summit-2017-cpan-and-perl6/

**Comment by ufobat** [comment]
I am going to Take Care of ist in 2 days :)

**Comment by ufobat** [comment]
<zengargoyle> woot: 1 |Zef::Repository::Ecosystems<cpan>|Bailador:ver('0.0.4')
