### ISSUE TITLE
BAILADOR=port:5000 is not honored

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#136]
Also worth noting that what seems like a debug note is repeated 5 times.

jgoff@Berdle:~/Documents/Repositories/drforr/angular-perl6-blog$ BAILADOR=port:5000 perl6 app.pl                                                                
key: port value: 5000
key: port value: 5000
key: port value: 5000
key: port value: 5000
key: port value: 5000
Entering the dance floor: http://127.0.0.1:3000 <-- port 3000, not 5000
[2017-06-11T08:56:54Z] Started HTTP server.

app.pl here:
--- cut here ---
use v6;
use Bailador;
use Bailador::Route::StaticFile;
Bailador::import();

my $version = '0.01';

get '/' => sub {
    template 'index.tt', { version => $version }
}

baile;
--- cut here ---

**Comment by ufobat** [comment]
Thanks for the Bug Report. I hope it is fixed in bdaa4137957ac5a78c5aed13ba09fef542fd74e1
