### ISSUE TITLE
Please add HTTP 4XX and 5XX error responses to a log

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#137]
When the Bailador server logs a request like:

[2017-06-11T09:49:41Z] GET /css/bootstrap.min.css HTTP/1.1

a response like:

[2017-06-11T09:49:42Z] GET /css/bootstrap.min.css --> 404

would be very useful. If you're developing an application on your own, it's easy to see the 404 or 500 errors in your browser, or web console. When the application gets out into the real world, though, and someone changes a web template but forgets to update a route, this may be the only way an administrator or someone debugging the back end will know that there's a problem - they certainly won't be clicking on all of the URLs on the site and making search requests from DDG in order to find all possible 404 links.

**Comment by ufobat** [comment]
error logging via Log::Any is available since 6aa768347162ace6db8573af6f796bfcefbd79f4.
