### ISSUE TITLE
A listing of all routes that the application can handle would be nice.

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#138]
Even if it's just a simple JSON form like:
{
  "GET /" => "app.pl:32",
  "GET /post:id" => "app.pl:75"
}

with "METHOD route" => "filename:line"

would help people keep track of the routes available - It could even be invoked with a separate --verbose flag upon startup, but Catalyst has this feature and it helps in tracking down problems there.

**Comment by perlpilot** [comment]
I made a quick prototype that doesn't list the filenames or line numbers (nor does it try to work for all cases).  Even something like this would be nice.  https://github.com/Bailador/Bailador/compare/dev...perlpilot:routes-list  The output of the example program looks like this:
```
GET	/
GET	/foo
GET	/foo/bar
POST	/blah/:order
GET	/blah/:order
PATCH	/goober/:order
```

**Comment by ufobat** [comment]
Cool. Thanks!
Maybe it would be a good idea to make this available within a `Bailador::Command` so in the end this command invoked on a shell
`> bailador list-routes my-app.pl6` 
would give this output
