### ISSUE TITLE
In README.md, Bailador:App 'sessions-config' does not exist.

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#139]
The actual error is below - this is from https://github.com/Bailador/Bailador#web-applications-via-inheriting-from-bailadorapp - the "Web applications via inheriting..." section.

-- cut here --
jgoff@Berdle:~/Documents/Repositories/drforr/angular-perl6-blog$ perl6 app.pl
No such method 'sessions-config' for invocant of type 'AngularWebSockets'
  in submethod BUILD at app.pl line 12
  in block <unit> at app.pl line 50
-- cut here --

**Comment by ufobat** [comment]
It is just config(), i think. It was recently changed by me. Its a Bug in the readme.

**Comment by ufobat** [comment]
Thanks for the bug report. :-) it's fixed
