### ISSUE TITLE
Root directory is off by one layer in the Web Application by Inheritance README section

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#140]
One too many layers of .parent in the example, I think - Hopefully this doesn't vary based upon where you actually execute the application from, that could be an issue.

-- cut here --
class MyApp is Bailador::App {
	submethod BUILD(|) {
		my $rootdir = $?FILE.IO.parent;#.parent; <-- Remove one layer of .parent, $rootdir is now correct.
-- cut here --

**Comment by drforr** [comment]
This is true for the example directory layout created by 'bailador --new=application-name', but if you move app.pl into a new bin/ directory, it breaks. Not surprising; maybe since app.pl is only run once, there can be a shim that checks that $?FILE has 'views/' at the same directory level, or looks one level up?

**Comment by drforr** [comment]
In the long run, maybe it's better to have bin/{app,app-prod,app-staging}.pl available instead?

**Comment by ufobat** [comment]
i can not remember in which ticket this was fixed, but it is now working as expected
