### ISSUE TITLE
Bailador::Route::StaticFile should return 404 when a file is not found.

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#141]
Also, the application should log to an error stream along with returning False. I got a bit confused when I saw the application return 302 Found for files that I knew I didn't have.

**Comment by ufobat** [comment]
could you please describe what you did? I think the only 302 gets returned if you call `redirect`. 

when I start the examples/app.pl and GET the index.htm, which is not existing, I am getting a 404.

```
> curl -v 'http://localhost:3000/index.htm'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /index.htm HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/html, charset=utf-8
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
Not found%            
```

**Comment by drforr** [comment]
It might very well simply be route chaining at work and my sloppy thinking - My file handler fails, and I might have been thinking returning False returns a 404 to the app rather than chaining to the next route that could handle it, so I would be thinking "But I returned False, why am I not getting a 404?" when "But I returned False.. Oh, right, I have to set the error code in order to break the chain."
