### ISSUE TITLE
Request to make 'views/' directory configurable

### ISSUE THREAD

**Issue by drforr** [Bailador/Bailador#142]
MVC layout is just fine, and I'm sure that lib/App/{Model,Controller} will be standard eventually. I'm just working with JavaScript projects which have other layouts in mind, and being able to configure 'views/' to be in .. say, 'src/views/' to be more in-line with how Angular does things.

**Comment by ufobat** [comment]
Thanks Emeric!

**Comment by drforr** [comment]
Party *on*!
