### ISSUE TITLE
Non-Bailador @*ARGS getting rejected when passing arguments to a script that wraps baile

### ISSUE THREAD

**Issue by scmorrison** [Bailador/Bailador#148]
Here is an example of what I am getting at:

```perl6
# baile-test.pl6

#!/usr/bin/env perl6

use v6;

use Bailador;

sub run-baile($extra) {
    # do something important with $extra
    # ...
    get '/' => sub { "hello world" }
    baile;
}

sub MAIN(:$extra = "default extra") {
    say "Using: $extra";
    run-baile($extra);
}
```
Running that script like this works fine:

`./baile-test.pl6`

Running it like this:
`./baile-test.pl6 --extra="passed extra"`

Throws this error:
```
Using: passed extra
--extra=passed extra not yet implemented. Sorry.
  in method get-command at /home/sam/.perl6/sources/A498112AD57B80B85FC619CAF9A94E97B75FA5D2 (Bailador::Commands) line 25
  in sub baile at /home/sam/.perl6/sources/F4CABBDF706A3C25D26ADB4440340E40CC98DAF9 (Bailador) line 124
  in sub run-baile at ./baile-test.pl6 line 9
  in sub MAIN at ./baile-test.pl6 line 14
  in block <unit> at ./baile-test.pl6 line 12
```

**Comment by scmorrison** [comment]
Currently all tests pass without the `@*ARGS` referenced in `App.pm`. Can you explain how you want to utilize `@*ARGS` -> `$*ENV`? I will then build some test coverage around the intended usage and work from there.

**Comment by ufobat** [comment]
There are now different commands located in `Bailador::Command`. The idea behin that is quite Mojo like. Each command behaves differently, There is `easy`for HTTP::Easy, there is `p6w` which returns a p6w app (for example for crustup) and there is `watch` which actually watches changes on your local file system.
the `watch` command has a paramter -w that can be used to specify which folders to watch for changes.

My unseccusssful fiddling around with this `@*ARGS` was a try to  invoke different commands ( the `@*ARGS.shift` ) and set paremters for your Bailador::Configuration.

bin/bailador has a watch command; I think other commands could/should be introduced this way.

For configuration settings Bailador currently checks for %*ENV<BAILADOR> and parses this string. This string is a key value list. I think bin/bailador just needs a --config parameter which appends? (maybe replaces) this "key - value - list - thingy".

hope this helps,
(ps: feel free to join our slack channel which is mentioned in the readme)

**Comment by scmorrison** [comment]
Thanks for the explanation. I will join the slack channel later tonight. As an example usage for `bailador`, you are thinking something along these lines:

```
bailador --w=views,public  \
    --config=debug,host:0.0.0.0,port:5000,miscextra=somethingextra,command=p6w
```

And then we either add those to `%*ENV` or some config hash that is passed around?

**Comment by ufobat** [comment]
for the watch command (where -w is available) it could be something like:

`bailador watch app.pl -w views,public --config=mode:development,port:5000`

**Comment by ufobat** [comment]
in general i was thinking of 
`bailador <command> --paramters...`

to be a bit closer to your example where you stated `command=p6w`, there is a `default-command`in the configuration: https://github.com/Bailador/Bailador/blob/dev/lib/Bailador/Configuration.pm#L21
if you set this value, for example if you invoke this example on a shell

`> BAILADOR="default-command:p6w" perl6 your-app.pl6` 

you would ask bailador to return a p6w app, ( https://github.com/Bailador/Bailador/blob/dev/lib/Bailador/App.pm#L88 )  which would of course not make much sense, because there is no http server to execute your p6w app

for example this should work and make sense:
`> BAILADOR="default-command:watch" perl6 your-app.pl6`

**Comment by scmorrison** [comment]
ok, thanks. That clarifies most of the questions I had. What about capturing misc user config options that they want to pass through to their app? I think Dancer2 does something like that.

**Comment by ufobat** [comment]
Fixed
