### ISSUE TITLE
create README.pod so README.md can be autogenerated from App::Mi6

### ISSUE THREAD

**Issue by ufobat** [Bailador/Bailador#151]
a README.pod is probably required for CPAN

**Comment by szabgab** [comment]
Personally I think it would be better to have the documentation only on bailador.net
generated from the README.md

**Comment by ufobat** [comment]
its probably hard because of the badges in the README.md

**Comment by ufobat** [comment]
https://github.com/skaji/mi6/commit/0ef385c96e0d5ed189669aa72c5f77630d1a8924
its possible to skip README.md generation with a dist.ini.
