### ISSUE TITLE
No such method 'to-psgi-app' for invocant of type 'Bailador::App'

### ISSUE THREAD

**Issue by scmorrison** [Bailador/Bailador#153]
This example no longer works. 

```perl6
use Bailador;

# simple cases
get '/' => sub {
    "hello world"
}

app.to-psgi-app;
```

`crustup --server HTTP:::Easy example.p6w`

I am seeing this error:

```
No such method 'to-psgi-app' for invocant of type 'Bailador::App'
```

Not yet sure what broke this....

**Comment by ufobat** [comment]
The example outdated. I missed to Change it when i wrote the Bailador::Command stuff.
The last Line should be baile()

**Comment by scmorrison** [comment]
Ok, thanks.

**Comment by ufobat** [comment]
I am doing to fix the documentation.

**Comment by ufobat** [comment]
fixed :)
