### ISSUE TITLE
Async operation

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#163]
@zoffixznet made a commend on my Facebook post about the need for async operations in Bailador. 

Make request handling concurrent to allow for longer responses as well.

Basically, there needs to be a way to make this app not block all requests while evaluating the current one. Presumably by just accepting a promise as the return value:

```
use Bailador;

get '/' => sub {
say "In";
await Promise.in(30);
say "out";
"foos";
}

baile();
```

**Comment by ufobat** [comment]
I think i'd like to have Bailador::Server in a own repo because it's a plain p6w http server

**Comment by ufobat** [comment]
we should write a async example application. maybe something with SSE?

**Comment by Emeric54** [comment]
We have a new issue, so we can close this one.
