### ISSUE TITLE
 bailador watch app.pl6 - watch the file being executed

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#166]
If I launch ` bailador watch app.pl6` I'd like to have the app.pl6 being watched for changes. By default.

**Comment by ufobat** [comment]
maybe it would be nice if you could state that you want to watch directores and files for changes.

**Comment by szabgab** [comment]
I am not sure if such fine-grained solution is required. For now the file being executed would be enough.

**Comment by ufobat** [comment]
the command line Switch -w can also watch files now, since it was easy to implement
