### ISSUE TITLE
bailador watch api.pl6 - cannot run if there is no lib directory

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#167]
In v0.0.5

```
$ bailador watch api.pl6
Attempting to boot up the app
```

After creating a either a directory called `lib` or a directory called `bin`, the above command is successful.

```
$ bailador easy api.pl6
```
works even without those directories.

**Comment by ufobat** [comment]
Files that do not exists are getting removed from the watchlist. According to Ticket #166 the file that you are executing is now also being watched. This means there can't be an empty watchlist. so it just works ;-)
