### ISSUE TITLE
Headers of 404 page vs static pages

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#170]
The default 404 page returns a header

```
["Content-Type" => "text/html, charset=utf-8"]
```

The static page handler, when serving plain text files returns
```
["Content-Type" => "text/plain;charset=UTF-8"];
```

Besides the expected difference of text/html vs text/plain there are 2 more differences that IMHO should not be. , vs. ;   and utf-8 vs UTF-8.
I think it would be better if this was unified across the whole Bailador.

**Comment by ufobat** [comment]
According to https://tools.ietf.org/html/rfc2616#section-3.7 error handlers return the same charset notation as the static page handler

**Comment by szabgab** [comment]
My point is that in Bailador they are different. Similar, but not exactly the same. See the two cases in my original comment. I think it would be better if they were exactly the same.

**Comment by ufobat** [comment]
aye! i missed text/plain vs text/html, sorry.

**Comment by ufobat** [comment]
I am going to revert this commit, because rendering string like `Not found` or `Internal Server Errors` are in fact plain text instead of html, as soon as you use a custom error (e.g. template or error_handler) the content type would be text/html.

**Comment by szabgab** [comment]
```
$ curl -I https://google.com/abc/def | grep Content-Ty
Content-Type: text/html; charset=UTF-8
```
So maybe the default of Bailador should be also some nicer HTML.

**Comment by ufobat** [comment]
Aye. I've created #188 for this so we can close this issue.

**Comment by szabgab** [comment]
There is another issue here I have not addressed yet. Please look closely in the original comment. There is also a difference in ; vs , and lowercase vs uppercase UTF. I think it would be better to unify those as well even if both are acceptable by the standards.

**Comment by ufobat** [comment]
I tought I've changed all occurances of `,` and lowercase to `;` with uppercase in https://github.com/Bailador/Bailador/commit/9ac2bd64892409823630fa0f4d3b532cfc20e95d.
Did i miss something?

**Comment by szabgab** [comment]
If I now run `grep Content t/*` I get lines like these:

```
t/11-error-templates.t:    is-deeply %resp<response>, [500, ["Content-Type" => "text/plain;charset=UTF-8"], 'Internal Server Error' ], '500 - without error template';
t/11-error-templates.t:    is-deeply %resp<response>, [500, ["Content-Type" => "text/html;charset=UTF-8"], 'muerte' ], '500 - with error template';
t/12-duplicate.t:is-deeply get-psgi-response('GET', '/foo'),  [200, ["Content-Type" => "text/html"], "hello"],              'route GET /foo exists';
```
so as I can see in some cases we get charset in some cases we don't. I think when we don't send the charset then it appears differently.

**Comment by ufobat** [comment]
I see! Will fix that :)
