### ISSUE TITLE
:name in the route should not match /

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#177]
given a route definition
```
get ‘/name/:name’  => sub ($name) {}
```
The request `/name/foo/bar` should not be accepted.

Currently it accepts it and puts  “foo” in $name 

Tests case added to t/30-examples-app.t

**Comment by ufobat** [comment]
**I considder this solution as a work around.**

Now all non prefix routes are supposted to match with having no postmatch content. 

This is probably not always right, because assumig this code
 
       get rx/ '/digit/' ( \d )   / => sub ($d) { ... }

you could expect it to match on `/digit/123` with $d == 1
