### ISSUE TITLE
Installation error on Windows 10

### ISSUE THREAD

**Issue by bapcyk** [Bailador/Bailador#184]
When I try to install Bailador on Windows 10 with zef (zef install bailador), I get:

===> Searching for: bailador
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: Digest, Digest::HMAC, HTTP::MultiPartParser, HTTP::Server::Ogre, Log::Any, Path::Iterator, YAMLish
===> Searching for missing dependencies: Test::META, HTTP::Request::Supply
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
No extracting backend available
  in method extract at C:\rakudo\share\perl6\site\sources\117C49F875FB3207907361DBF52BF2B5520F348F (Zef::Extract) line 9
  in code  at C:\rakudo\share\perl6\site\sources\58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 260
  in method extract at C:\rakudo\share\perl6\site\sources\58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 243
  in method fetch at C:\rakudo\share\perl6\site\sources\58A2CF7B6756361E028457049819328DE7AF8AD8 (Zef::Client) line 182
  in sub MAIN at C:\rakudo\share\perl6\site\sources\B9B6B5F22DE3727E789C70B98CFB4A5030EE58D8 (Zef::CLI) line 149
  in block <unit> at C:\rakudo\share\perl6\site\resources\781A78D3FE358EE90D60E4633882482D3AE9D3A5 line 1

Perl6 version is:

This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-53-g66c6dda
implementing Perl 6.c.

**Comment by szabgab** [comment]
That looks like `zef` is missing something. 

*No extracting backend available* seems to be the problem.

Could you please paste here what `zef info zef` says?

**Comment by szabgab** [comment]
Closing due to lack of feedback. Please reopen it if the problem persists and if you can provide more details.

**Comment by bapcyk** [comment]
I am sorry my belated answer.
zef info zef output:
```
- Info for: zef
- Identity: zef:ver('0.1.19'):auth('github:ugexe')
- Recommended By: C:\rakudo\share\perl6\site
Description:     It's like [cpanm] wearing high heels with a tracksuit
License:         Artistic-2.0
Source-url:      git://github.com/ugexe/zef.git
Provides: 36 modules
Support:
#   bugtracker: https://github.com/ugexe/zef/issues
Depends: 0 items
```
