### ISSUE TITLE
pass arbitrary header to run-psgi-request

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#196]
An application might requires an API-KEY in the header of the request. AFAIK currently the only thing we can pass to the header of a test-request is the 'http_cookie'. We should be able to pass arbitrary key-value pairs.

Maybe it could accept something like 

```
header => {
   :key(value),
}
```
and then the `http_cookie` could be part of it.

**Comment by ufobat** [comment]
isn't this done?
