### ISSUE TITLE
Still giving non-fatal Failed test 'route GET /hello/Foo.html'

### ISSUE THREAD

**Issue by sed76** [Bailador/Bailador#226]
It gives 'Custom 404 page' instead of expected result.  :)

```
MBP-Sergej:~ sed$ zef install Bailador
===> Searching for: Bailador
===> Testing: Bailador:ver('0.0.9')
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.

    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 90
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2
===> Testing [OK] for Bailador:ver('0.0.9')
===> Installing: Bailador:ver('0.0.9')

1 bin/ script [bailador] installed to:
/usr/local/Cellar/rakudo-star/2017.07/share/perl6/site/bin
```

**Comment by ufobat** [comment]
that's not a failure during the installation.
With `use Test` you can mark tests as "todo", thats basially a different type of skipping a Test. Documentation regarding this feature of Test can be found here: https://docs.perl6.org/language/testing#index-entry-todo-todo%28%24reason%2C_%24count_%3D_1%29

So what you are seeing is the todo output of a test that is not yet implemented in Bailador. In this case it is the feature that was requested in this ticket #178.

Unfortunatelly you can't tell from the output that you've provided that this is a skipped test.

**Comment by szabgab** [comment]
This noisy reporting is an issue with Test.pm6 that comes with Rakudo 2017.07
It has been fixed since then and will be in the next release of Rakudo
https://rt.perl.org/Public/Bug/Display.html?id=131767

**Comment by szabgab** [comment]
In any case, thanks for reporting!

**Comment by sed76** [comment]
Hmm... Didn't knew. Thank you!
