### ISSUE TITLE
===SORRY!=== P6M Merging GLOBAL symbols failed: duplicate definition of symbol Response

### ISSUE THREAD

**Issue by nige123** [Bailador/Bailador#229]
After installing Bailador on moarvm 2017.07 with:

shell> zef install --force-tests. I install HTTP::UserAgent 

I then receive the following error when starting up Bailador:

P6M Merging GLOBAL symbols failed: duplicate definition of symbol Response

**Comment by szabgab** [comment]
How did you "start up" Bailador?

**Comment by nige123** [comment]
Just from the command line:

shell> perl6 lib/App.p6

**Comment by szabgab** [comment]
The right way to launch a Bailador app is
```
bailador watch bin/app.pl6
```
or if you have the code ending with `bailador` in  `lib/App.p6` then
```
bailador watch lib/App.pl6
```

**Comment by ufobat** [comment]
imho the command `perl6 lib/App.p6` is fine if and should work. but `P6M Merging GLOBAL... ` is kinda strange.. Did I understand it right, it is just happening if you install HTTP::UserAgent as well. without it is working?

**Comment by szabgab** [comment]
I guess we should ask what is in that `lib/App.p6` :)

**Comment by ufobat** [comment]
https://github.com/sergot/http-useragent/issues/178
