### ISSUE TITLE
Bailador error "Too few positionals passed; expected 2 arguments but got 1.......

### ISSUE THREAD

**Issue by anopperl** [Bailador/Bailador#232]
Bailador error 

i am using Ubuntu 16.04

version :
This is Rakudo version 2016.04 built on MoarVM version 2016.04
implementing Perl 6.c.

output :
zef install Bailador
===> Searching for: Bailador
Too few positionals passed; expected 2 arguments but got 1
in code at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources/8AD1A00491891C80B38B96B3FA4DD2597CC594F6 (Zef::Repository::LocalCache) line 91
in method slurp-package-list at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources/8AD1A00491891C80B38B96B3FA4DD2597CC594F6 (Zef::Repository::LocalCache) line 89
in method gather-dists at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources/8AD1A00491891C80B38B96B3FA4DD2597CC594F6 (Zef::Repository::LocalCache) line 109
in code at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources/8AD1A00491891C80B38B96B3FA4DD2597CC594F6 (Zef::Repository::LocalCache) line 58
in code at sources/1CAA5551B98C09A79B5E15791ABE848C8B61B218 (Zef::Repository) line 13
in method candidates at sources/1CAA5551B98C09A79B5E15791ABE848C8B61B218 (Zef::Repository) line 10
in method find-candidates at sources/2EF4A9248D331CAC705E994F2309B345CBDAC9FF (Zef::Client) line 107
in method find-candidates at sources/2EF4A9248D331CAC705E994F2309B345CBDAC9FF (Zef::Client) line 90
in sub MAIN at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/sources/F072F63691062706B5BD9BA86738DB75BCE55019 (Zef::CLI) line 132
in block <unit> at /home/anopperl6/rakudo/rakudo-star-2016.04/install/share/perl6/site/resources/3EA9A42F99F12D65FC93EB509D2D5349377D2866 line 1

**Comment by szabgab** [comment]
That's a very old Rakudo. Please install Rakudo Star 2017.07 and try again.

**Comment by anopperl** [comment]
Dear Gabor, 

its working. 
i am big fan of you. i have been following for 7 years.
thanks you very much Gabor

**Comment by szabgab** [comment]
👍
