### ISSUE TITLE
self.get and self.post don't work

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#234]
The README suggests
`self.get`
and 
`self.post`

but neither seem to work. "No such method"
Using Bailador 0.0.10

If they are not supported now then we should remove them from the readme file.

**Comment by hipek8** [comment]
Had same problem, seems like they were removed in this version. I had to add
`method get($x) { self.add_route: make-simple-route('GET', $x) }`
to subclass I use

**Comment by ufobat** [comment]
removed from the documentation. Please have a look at the Controler Classes which was introduced in 0.0.11
