### ISSUE TITLE
clean up the example directory

### ISSUE THREAD

**Issue by ufobat** [Bailador/Bailador#241]
it would be nice if each example would be placed in a seperate directory. and maybe a README.md per directory, explaining what this example is about.
currently everything is in one directory. i am afraid this is rather confusing

**Comment by szabgab** [comment]
Separating into directories is a good idea. I've also started to add information about some of them in the main README.md I think that would be a better place for the explanations with proper links to the directory and also to the respective test file.

**Comment by szabgab** [comment]
All of them were moved to to separate directories. Some of them even got new test cases.

**Comment by ufobat** [comment]
Thank you gabor!
