### ISSUE TITLE
create /doc directory and split README into smaller parts

### ISSUE THREAD

**Issue by ufobat** [Bailador/Bailador#245]
This makes #151 more easy.
in addition it allows to have simple guieds like "Getting-Started".

I hope this makes it more easy for the user to find what he's looking for.

**Comment by szabgab** [comment]
I personally prefer the one large page approach, but having both split and single-page format on the web site is much easier if the source files are split up.

**Comment by ufobat** [comment]
are the specific benefits from having one large file?

**Comment by szabgab** [comment]
I like when I don't have to click 3 links to get to an answer but I can search just a single page.
