### ISSUE TITLE
Example to spread application routes across multiple files

### ISSUE THREAD

**Issue by hythm7** [Bailador/Bailador#261]
Hello, This is not an actual issue with Bailador, I  just wanna know if there is away to spread application accros multiple files. What I'm doing now is I  `use Bailador;` on top of each file in my App routes directories, does that create a separate Bailador app for each file? Is there example on how to organize Bailador app on multiple directores?
Thanks.

**Comment by ufobat** [comment]
that soudn't be a problem if you use Bailador in different files. I am doing the same in my toy-app: https://github.com/ufobat/VoteImproved

**Comment by hythm7** [comment]
@ufobat Thank you, the toy-app is exactly the example I was looking for.
