### ISSUE TITLE
Cannot resolve caller AUTOGEN

### ISSUE THREAD

**Issue by Tyil** [Bailador/Bailador#262]
I'm getting the following error when trying to use Bailador:

```
Cannot resolve caller AUTOGEN(Bailador::App: Int); none of these signatures match:
    (Bailador::App $: *%_)
    (Bailador::App $: Str $command, *@args, *%_)
  in sub baile at /home/tyil/rakudobrew/moar-nom/install/share/perl6/site/sources/6F33C03589936F3E254B5C14BC95945C77196A75 (Bailador) line 157
  in block <unit> at t.pl6 line 9
```

The script I'm running is

```
#! /usr/bin/env perl6

use Bailador;

get "/" => sub {
	say "hi";
}

baile(8000);
```

`perl6 --version`: `This is Rakudo version 2017.08-108-g760530a built on MoarVM version 2017.08.1-150-g0b81969`. This perl6 was compiled with `rakudobrew build moar`. I've also tried a MoarVM configured with `--has-libffi`. The result is the same.

OS is Ubuntu 16.04.3, running as a VM with `vm-bhyve` on FreeBSD 11.

**Comment by ufobat** [comment]
the call to `baile(8000);` is wrong
try this:

```perl6
#! /usr/bin/env perl6

use Bailador;
config.port = 8000;
get "/" => sub {
	say "hi";
}

baile();
```

**Comment by Tyil** [comment]
That was an easy fix. I seem to have copied code from an old source. Thanks for the help!
