### ISSUE TITLE
Paths hardcoded to moar-nom

### ISSUE THREAD

**Issue by AlexDaniel** [Bailador/Bailador#278]
https://github.com/Bailador/Bailador/blob/b9a03bd708b59de288b07ddbac95f2669195be1f/ducky.json#L31

I'm not quite sure what this line is trying to achieve (`/root/`?), but “nom” is no longer used and it should be “master”.

Two other weird cases:
https://github.com/Bailador/Bailador/blob/b9a03bd708b59de288b07ddbac95f2669195be1f/xt/20-cli.t#L20
https://github.com/Bailador/Bailador/blob/b9a03bd708b59de288b07ddbac95f2669195be1f/xt/20-cli.t#L21

**Comment by ufobat** [comment]
the 2 wired cases are just comments, which indeed don't make much sense..

@melezhik could you have a look at the ducky.json file?
