### ISSUE TITLE
Request: Installation Instructions for users and developers

### ISSUE THREAD

**Issue by brianwisti** [Bailador/Bailador#28]
Please add requirements and installation instructions to the README.md and possibly the Bailador POD.
- Should regular users install via `panda install Bailador`?
- How should those who want to work directly with the github source build,  test, and install Bailador? I had no idea what to do with a fresh checkout.

**Comment by tadzik** [comment]
Hm, valid concern. Then again, I feel like every single module in our ecosystem needs such a thing in this case. It'd be nice to have a common README template that describes it all. Worth looking into, perhaps it'll suffice to cargo-cult whatever Perl 5 is doing, I seem to recall they have something like that. Thanks for bringing it up!

**Comment by szabgab** [comment]
Added both. Please check if they make sense.
