### ISSUE TITLE
params for layouts

### ISSUE THREAD

**Issue by interlab** [Bailador/Bailador#306]
Windows 10
Rakudo Star version 2018.04.1 built on MoarVM version 2018.04.1 implementing Perl 6.c.

why can not I pass a parameter to the layer, but only to the content?
for example, I want to set the value of a page in a layout <title><%= $title %></title>

```
layout.html:
<html><head>
<title>???</title>
</head>
<body>
 content.html  <-- all parameters go here
</body>
</html>
```

**Comment by ufobat** [comment]
that should be easy to fix :-)
thanks for reporting the bug!

**Comment by ufobat** [comment]
fixed in dev branch. could you give me feedback if it works for you, please?
keep in mind that when you create your layout.template file that the first paramter is still the $content, than your parameters get passed.

```
my ($content, $the, $rest) = @_;
```

**Comment by interlab** [comment]
works!
