### ISSUE TITLE
Default project dies with a broken Promise (GET /)

### ISSUE THREAD

**Issue by cfa** [Bailador/Bailador#313]
Project created and launched with:

```
$ bailador new foo
$ cd foo
$ p6 bin/app.pl6
Entering the dance floor: http://127.0.0.1:3000
```

Attempting to GET http://127.0.0.1:3000 (e.g., `curl http://127.0.0.1:3000`) dies with:

```
Tried to get the result of a broken Promise
  in sub encode-psgi-response at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/C3577325076AA02263D770AD0F22D36E14F81568 (PSGI) line 94
  in method handler at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/DC7C76DF1185915F747BB7F062925CE7CDEEC2C5 (HTTP::Easy::PSGI) line 47
  in method run at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 186
  in method run at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/3D10CEB91D5C9A4F4C7242ED66C3F801BC36AC70 (Bailador::Command::easy) line 19
  in method baile at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/3B59FEB171998559116B8EFDCCE6CFDD218798CB (Bailador::App) line 295
  in method baile at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/3B59FEB171998559116B8EFDCCE6CFDD218798CB (Bailador::App) line 280
  in sub baile at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/D817487F881DBC8C1A787DB15433AE23481E9ACB (Bailador) line 162
  in block <unit> at bin/app.pl6 line 10

Original exception:
    Cannot modify an immutable 'Any' type object
      in method dispatch at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/3B59FEB171998559116B8EFDCCE6CFDD218798CB (Bailador::App) line 336
      in block  at /Users/cfa/.rakudup/2018.12/install/share/perl6/site/sources/3B59FEB171998559116B8EFDCCE6CFDD218798CB (Bailador::App) line 320
```

Problem encountered with 2018.12 on both macOS and Debian, `Bailador:ver<0.0.17>:auth<github:Bailador>`.

**Comment by ufobat** [comment]
I am wondering whether this [line](https://github.com/Bailador/Bailador/blob/dev/lib/Bailador/Context.pm#L7) just needs a `is rw`. But if so why did it ever work 🤷‍♂️

**Comment by ufobat** [comment]
https://github.com/rakudo/rakudo/commit/7d37f9aaf0ef0290709679568dac0b6110c43506

**Comment by ufobat** [comment]
Did you do anyting special which is not mentioned in the ticket? I am not able to reproduce this :-(

**Comment by cfa** [comment]
Not that I'm aware of.

Experienced on two different platforms with 2018.12 and the latest (at the time) set of dependencies installed with `zef`. No changes were made to the generated tree.

**Comment by cfa** [comment]
Just updated to `Bailador:ver<0.0.18>:auth<github:Bailador>`, which pulled in some fresh dependencies:

    ===> Testing [OK] for Bailador:ver<0.0.18>:auth<github:Bailador>
    ===> Installing: IO::Glob:ver<0.6>:auth<github:zostay>
    ===> Installing: Path::Finder:ver<0.2.0>
    ===> Installing: Bailador:ver<0.0.18>:auth<github:Bailador>

I'm no longer seeing the exception.
