### ISSUE TITLE
POST Params are not there

### ISSUE THREAD

**Issue by zoffixznet** [Bailador/Bailador#43]
It seems POSTed params are not passed any more.

This can be seen with errors in [postapp](../blob/master/examples/postapp.pl) and [pastebin](../blob/master/examples/pastebin.pl) always saying `No empty pastes please`.

**Comment by zoffixznet** [comment]
It look like this is caused by Bailador using keys like `psgi.input`, when it's now called `p6sgi.input` (notice the 6).

**Comment by AlexDaniel** [comment]
Same problem here.

**Comment by AlexDaniel** [comment]
Oh, it seems like https://github.com/tadzik/Bailador/pull/44 is supposed to fix it.

**Comment by AlexDaniel** [comment]
Should be fixed, but are there any tests?

**Comment by szabgab** [comment]
There are already plenty of tests with POST.
