### ISSUE TITLE
Switching between different PSGI Servers

### ISSUE THREAD

**Issue by ufobat** [Bailador/Bailador#63]
Bailador should be able to return a PSGI App so it can run on various PSGI Servers.
PSGI Spec for perl6: https://github.com/zostay/P6SGI

**Comment by Altai-man** [comment]
It's easy to implement, but what are servers actually ready for it? Except for `HTTP::Easy::PSGI` we have `HTTP::Server::Tiny`, but it is unable to collect the headers properly.

**Comment by ufobat** [comment]
I think that this is almost done. You can use for example crustup to start your p6sgi app on top of any Server. Mostly documentation is missing.

**Comment by ufobat** [comment]
#78 is related

**Comment by Altai-man** [comment]
Crustup here truly seems useful.
Regarding that, we can only change `baile` sub appropriately to use it. We need to either preserve current default behaviour with `HTTP::Easy::PSGI` server and give an ability to get the p6sgi sub to use it with crustup or break the old api and rewrite `baile` to use with crustup only(and reflect it in the docs, add new dependency, etc). What will be more appropriate for a PR for this issue?

**Comment by ufobat** [comment]
I would suggest not to touch `baile()` yet since we know that running on top of `HTTP::Easy::PSGI` works quite okay. 

We're already able to get the psgi-app from the [Bailador::App](https://github.com/ufobat/Bailador/blob/master/lib/Bailador/App.pm#L67). It' is just [not yet possible](https://github.com/ufobat/Bailador/blob/master/lib/Bailador.pm#L10) to access the app directly when you're donig the classical approach of writing web apps.

docu for the plackup / crust way:  
* [perl5 Dancer](http://search.cpan.org/dist/Dancer/lib/Dancer/Deployment.pod#Running_on_Perl_webservers_with_plackup)
* [perl5 Mojo](http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#DEPLOYMENT)
* [packup](http://search.cpan.org/~miyagawa/Plack-1.0039/script/plackup)
* [crustup](https://github.com/tokuhirom/p6-Crust/blob/master/bin/crustup)

**Comment by ufobat** [comment]
closed because the "crustup" was is documented in README.md
