### ISSUE TITLE
Auto-Restart on Change

### ISSUE THREAD

**Issue by zoffixznet** [Bailador/Bailador#65]
It would be nice if in development mode the script would auto-restart when you make changes in the code. There'd be some default dirs, as well as some that users can add themselves, via command line arguments, for example. 

[IO::Notification::Recursive](http://modules.perl6.org/repo/IO::Notification::Recursive) can do the watching. Not sure how to easily do the restart.

**Comment by ufobat** [comment]
In Mojolicious thats done by the Morbo Web Server. http://mojolicious.org/perldoc/morbo . I like the Idea that the webserver itself checks for changed files. Restarting is basically just a re-invokation of the script/app.

The question is whether a development server is a project of its own or should be part of bailador itself. Either way, I'm in need of such a "thing" as well.

**Comment by zoffixznet** [comment]
I wrote this: https://github.com/zoffixznet/perl-Bailador-Dev-AutoRestarter

That works for me, so I dunno if you want to close this issue or leave it open and have something similar shipped with core Bailador eventually.

**Comment by ufobat** [comment]
That's awesome!
I'd love to have this in the core. The only thing i'd like to change for the future would be that the app ( https://github.com/zoffixznet/perl-Bailador-Dev-AutoRestarter/blob/master/bin/rebailador#L22 ) is a app in the sense of P6SGI/P6W . Give me a few more days befor Bailador returns / handles such a P6SGI app correctly.

> A P6SGI application is a Perl 6 routine that receives a P6SGI environment and responds to it by returning a response.
https://github.com/zostay/P6SGI/blob/master/README.md

**Comment by szabgab** [comment]
rebailador from perl-Bailador-Dev-AutoRestarter written by @zoffixznet is now included in Bailador.
