### ISSUE TITLE
Ideas for template caching

### ISSUE THREAD

**Issue by scmorrison** [Bailador/Bailador#97]
I wasn't sure if you had any plans for a caching module, but I would like to take a look into what is involved. My idea would be to build something similar to the Template modules for caching, starting with a simple in-memory cache.

Here is a test using the `Cache::LRU` module:

```perl6
#!/usr/bin/env perl6

use v6;
use lib 'lib';
use Cache::LRU;
use Bailador;
Bailador::import(rootdir => "./examples");

my $cache = Cache::LRU.new(size => 1024);

sub template-cache($template-name, %params) {
  my $key     = [$template-name, |%params.kv].join('-');
  my $content = $cache.get($key);
  return $content if $content.defined;
  return $cache.set($key, template('tmpl.tt', %params) );
}

get / ^ '/template/' (.+) $ / => sub ($x) {
  template-cache('tmpl.tt', { name => $x });
}

baile;

# Test with ab:
#
# ab -n 1000 -c 10 http://0.0.0.0:3000/template/bailador 
#
# with cache:
#  Requests per second:    165.66 [#/sec] (mean)
# without cache:
#  Requests per second:    23.88 [#/sec] (mean)
```

This is a simple example and not what I am imagining for a final implementation. But it does a good job demonstrating the need for a cache store. Please let me know if this is something you think is worth focusing on and any suggestions you might have for the implementation.

Thanks,
Sam

**Comment by ufobat** [comment]
Hey :-)
thanks for your suggestion. I am pretty surprised that the caching actually makes such a huge difference. 
The caching that I've added so far is just preventing from re-evaluating the template file into a code-ref. After the template is evaluated it is pretty much just a single sub call that you're saving.

The numbers of your benchmark stands for itself! I would be happy so see some pull requests! :)

**Comment by scmorrison** [comment]
ok, I will start looking into a few solutions for this. I think there needs to be a way to tie in a session ID with the cache key or something to distinguish distinct versions of the cached data that might have session-specific data associated with it.

**Comment by ufobat** [comment]
awesome :-)

**Comment by ufobat** [comment]
I forgot to merge a feature branch of mine into Bailador. The Template::Mojo Templates were parsed & compiled for each template() invocation. This should be much better now. If you like you could compare the speed once again :-)

**Comment by scmorrison** [comment]
Great work! Definitely much faster. It is very helpful to have that handled at the template level. Really speeds things up.

I have started https://github.com/scmorrison/perl6-Web-Cache to for handling the caching outside of the templating engine. This got me thinking about ways to handling partials, pre-generated content, with dynamic parts that need to be cached under different params.

One use case would be something like this:

```perl6
# Create a new cache store
my $memory-cache = cache-create-store( size    => 2048,
                                       backend => 'memory' );

get / ^ '/template/' (.+) $ / => sub ($x) {

    $memory-cache( key     => gen-complex-cache-key(url-for...),
                   content => {
                       my $session = session;
                       my %product_data = some-expensive-db-query(...);
                       template($template, %product_data)l
                   });
}
```

This will allow for passing a block to the cache where it only runs on the initial set and again when expired. This enables long running processes to be offloaded to the caching process entirely. For example, using `session` still causes slowness outside of the `content` block.

This also facilitates multiple cache blocks that can result in a composed page made from separate template parts (e.g. cached dynamic content sections for authenticated user vs guest). Still a lot of work to do...

```perl6
my $visible_to_everyone       = $memory-cache(....;
my $visible_to_authenticated  = $memory-cache(....;
my $additional_for_everyone   = $memory-cache(....;

return $visible_to_everyone ~ $visible_to_authenticated ~ $additional_for_everyone;
# also could be suitable for generating content for the template %context from the cached versions.
```

Next steps for this are to flush out key-based expiration functionality, a simple way to generate suitable cache keys, and start working out additional cache backend support (disk, memcached, etc.).

We can close this issue if you want. Your solution works great. I will keep tinkering with this `Web::Cache` module and hopefully make some progress. I have some ideas for a generic config module as well as a few helper routines that might be useful for `Bailador`. I will keep opening issues for new ideas. Thanks again!
